name: Build and run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run script
        run: |
          
          PASSWORD="${{ secrets.PASSWORD }}"
          USERNAME="${{ secrets.USERNAME }}"

          COMMIT_RANGE="${{ github.event.before }}..${{ github.sha }}"
          COMMIT_COUNT=$(git rev-list --count "$COMMIT_RANGE" || echo "1")
         
          mkdir build 2> /dev/null
          git show -n "$COMMIT_COUNT" --name-only | grep "/challenge/" | sed 's|\(.*challenge\)/.*|\1|' | uniq > build/changes.txt
          cat build/changes.txt
          
          echo "COMMIT RANGE: $COMMIT_RANGE"
          echo "COMMIT COUNT: $COMMIT_COUNT"

          chmod +x build.sh
          ./build.sh "$USERNAME" "$PASSWORD" "$COMMIT_COUNT"
